### PR TITLE
Updated and expanded readme

### PR DESCRIPTION
**Pull request by rfriberg**
Updated and expanded readme.

### CODE REVIEW

**Comment by kkowalsky** [comment]
this looks great @rfriberg!

**Comment by migurski** [comment]
Looks good! Having the version number in the README seems dangerous, because we will absolutely forget to update it when we make new releases. What else can we do with that?

**Comment by rfriberg** [comment]
@migurski we can drop the current version number.  @hanbyul-here added the version shield to the top of the page, so that will stay up-to-date.  I do still want to call out which versions of Leaflet and Tangram we are relying on, though. So, we will need to make README/doc updates a regular part of the release process.

**Comment by migurski** [comment]
Could we add a test of some form to auto-check this when deploying?

**Comment by hanbyul-here** [comment]
Shield will be updated automatically. I am not sure how we can update the version number of dependencies on docs automatically. (Especially Tangram, which is not part of package.json)

**Comment by hanbyul-here** [comment]
I and @rfriberg talked about this. Since we actually have to some manual works to bump up the version (Leaflet version is anchored to v1.0.1, Tangram script is string value), making 'update the docs' process as a part of the release seems to be our best option. We probably can have checklist on release.md what to do before release.

**Comment by kkowalsky** [comment]
That would be great!

in the :sparkles: glorious future :sparkles: we could explore other options like having an auto-updating button in the docs as well.

**Comment by rfriberg** [comment]
@hanbyul-here - I forgot about that demo.  Thanks for adding!

**Pull request merged**
