### PR TITLE
Upgrade to Tangram 0.12.x

### PR DESCRIPTION
**Pull request by bcamper**

### CODE REVIEW

**Comment by rfriberg** [comment]
Initial testing looks good @bcamper - anything in particular I should double-check?

I am getting a few console warnings when using our latest basemap styles.  They all appear to have to do with a missing 'order' parameter.  For example:
- `Tangram v0.12.0 [warn]: Layer 'landuse:tier6': 'order' parameter is required unless blend mode is 'overlay'`
- `Tangram v0.12.0 [warn]: Layer 'landuse:tier6:minor-landuse': 'order' parameter is required unless blend mode is 'overlay'`
- `Tangram v0.12.0 [warn]: Layer 'landuse:tier6:garden': 'order' parameter is required unless blend mode is 'overlay'`

I'm seeing these on latest Refill, Cinnabar, Walkabout, Zinc, and Tron.  cc/ @nvkelso

**Comment by dmvaldman** [comment]
Also you'll be able to import Tangram on this release instead of using it as a script tag. I'll make a PR.

**Comment by bcamper** [comment]
@rfriberg thanks - yes, we'll need to update basemaps to resolve those warnings, though they are harmless in and of themselves.

**Comment by rfriberg** [comment]
Tangram v0.12 is needed for a blog post going out shortly, so I'm going to merge this as is and release today.  We can work on importing/bundling properly after this release.

Any objections? cc/ @hanbyul-here @louh

**Comment by bcamper** [comment]
One interesting issue with bundling is that it will make using a custom version of Tangram more difficult (I think?). At a minimum, even if they coexist OK, you'll have to incur the network load for both. Not saying we shouldn't though, just to be aware...

**Pull request merged**
