### PR TITLE
removed attributionText (replaced with attribution)

### LINKED ISSUE #206: deprecate attributionText
- It basically does same thing as [attribution](http://leafletjs.com/reference.html#tilelayer-attribution) from Leaflet. no need to be there.

### PR DESCRIPTION
**Pull request by hanbyul-here**
- this pr didn't consider compability. Is there any place which is using `attributionText` ?? @binx @rmglennon @migurski 
- closes #206

### CODE REVIEW

**Comment by binx** [comment]
I used it in the updated borders repo, I'll change it now

**Comment by hanbyul-here** [comment]
@binx I made it compatible for now ( so it doesn't break while it is being waited for release) . so `attributionText` has more priority to `attribution` in this branch. Let's release this version first, then you can edit syntax to using `attribution` and then `attributionText` is going to be deprecated. (so that it doesn't have moment of breaking ⚡ )

**Comment by rmglennon** [comment]
There was an `attribution` in the original leaflet geocoder, which seemed to duplicate the `attributionText` from mapzen.js. I removed `attribution` from the documentation already, but we should make sure that version of `attribution` is not lingering in the geocoder.

This was in the geocoder docs: 
| attribution | _String_. Attribution text to include. Set to blank or `null` to disable. | Default string: `'Geocoding by <a href="https://mapzen.com/projects/search/">Mapzen</a>'` |

**Comment by hanbyul-here** [comment]
@rmglennon good point, I disabled the attribution from geocoder when I put mapzen branded attribution for mapzen.js

**Pull request merged**
