### PR TITLE
peg mapzen house styles to major version

### PR DESCRIPTION
**Pull request by nvkelso**
* point at major versions of Mapzen house styles (not unversioned latest) in basemapStyles.js
* ~~use Tangram v0.9 in tangram.js and in test.html~~

### CODE REVIEW

**Comment by nvkelso** [comment]
I think this is ready to go. I've verified all the new URLs do fetch content, but I haven't verified in a living mapzen.js build. 

@hanbyul-here @migurski Github is being fussy and not allowing a merge via the website, but via CL should work fine.

**Comment by nvkelso** [comment]
Ah, @hanbyul-here just merged in https://github.com/mapzen/mapzen.js/pull/234/files. I'll take ref to those files out of my PR.

**Comment by migurski** [comment]
Yeah, it's the Tangram version conflicts. Thanks for recommending a set of scene versions that will work!

**Comment by nvkelso** [comment]
Github's happy now :) All your's @hanbyul-here!

**Comment by hanbyul-here** [comment]
Does this also close https://github.com/mapzen/mapzen.js/issues/164 ? @nvkelso

**Pull request merged**
